name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git make clang perl unzip xz-utils curl

      - name: Install Theos
        run: |
          git clone https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos
          $THEOS/bin/update-theos

      - name: Build tweak
        run: |
          export THEOS=$HOME/theos
          make
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            packages/*.deb
            .theos/obj/debug/*.dylib
