name: build-tweak

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          clang \
          make \
          git \
          perl \
          fakeroot \
          dpkg-dev \
          unzip \
          wget

    - name: Install Theos
      run: |
        git clone https://github.com/theos/theos.git $HOME/theos

    - name: Install iOS SDK
      run: |
        mkdir -p $HOME/theos/sdks
        cd $HOME/theos/sdks
        wget https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mv sdks-master/* .
        rm -rf master.zip sdks-master

    - name: Build tweak
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        make package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tweak
        path: packages/*.deb
