name: build-dylib

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y clang make git perl unzip wget

    - name: Install Theos
      run: |
        git clone https://github.com/theos/theos.git $HOME/theos

    - name: Install SDK
      run: |
        mkdir -p $HOME/theos/sdks
        cd $HOME/theos/sdks
        wget https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mv sdks-master/* .
        rm -rf master.zip sdks-master

    - name: Build
      run: |
        export THEOS=$HOME/theos
        make

    - name: Upload dylib
      uses: actions/upload-artifact@v4
      with:
        name: dylib
        path: .theos/obj/debug/*.dylib
